### ISSUE TITLE
📌 [Roadmap] January 2022 - React / Components / Responsive / Flags / WasmWorkers

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/designto-code#105]
# January 2022 Update - Powerful Flags, Responsive Web development, Reliable Editor
> Working Draft of January Release, targeting Jan 25, tops. This will be the main roadmap in entire Grida subprojects for Dec-Jan

This Release will contain following key features & concepts
- More powerful design with flags
- Component / Instance Support
- Run Realtime React App on Web with Webworkers & Wasm integ.
- Complete Lints for - Layouting, Naming, Flags annotations.
- Documentations for Design Guide, Flags Demo
- Full Example Project

**Related**
- Grida Assistant Dec Release - https://github.com/gridaco/assistant/pull/186

### New Flags

**h1 - h6 element preference flags** - https://github.com/gridaco/designto-code/pull/106

- [x]  [`--as-h1`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h1)
- [x]  [`--as-h2`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h2)
- [x]  [`--as-h3`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h3)
- [x]  [`--as-h4`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h4)
- [x]  [`--as-h5`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h5)
- [x]  [`--as-h6`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-h6)
- [x]  [`--as-p`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-p)
- [x]  [`--as-span`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-span)

**min/max/fix width height declaration flags** - https://github.com/gridaco/designto-code/pull/106

- [x]  [`--width`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--width)
- [x]  [`--height`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--height) 
- [x]  [`--max-width`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--max-width)
- [x]  [`--min-width`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--min-width)
- [x]  [`--max-height`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--max-height)
- [x]  [`--min-height`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--min-height) 
- [x]  [`--fix-height`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--fix-height)
- [x]  [`--fix-width`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--fix-width)

**WIP** - https://github.com/gridaco/designto-code/pull/107
- [ ]  [`--module`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--module)
- [ ]  [`--text-template`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--text-template)
- [ ]  [`--video`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--video)
- [ ]  [`--is-input-caret`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--is-input-caret)
- [ ]  [`--break-component`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--break-component)
- [ ]  [`--as-modal`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-modal)
- [ ]  [`--motion-on-hover`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--motion-on-hover)
- [ ]  [`--ignore`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--ignore)
- [ ]  [`--hash`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--hash)
- [ ]  [`--motion`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--motion)
- [ ]  [`--as-input`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-input)
- [ ]  [`--as-button`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--as-button)
- [ ]  [`--onclick`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--onclick)
- [ ]  [`--cursor`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--cursor)
- [ ]  [`--href`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--href)
- [ ]  [`--id`](https://github.com/gridaco/designto-code/tree/support-flags/packages/support-flags/--id)

**Proposal Work in progress**
- [ ]  https://github.com/gridaco/designto-code/issues/91
- [ ]  https://github.com/gridaco/designto-code/issues/92

## New Lints
- [ ] `Suggestion: Use Autolayout`
- [ ] `Warning: Avoid using Group (Use Frames Instead)`

**Fixes**
- [ ] Alignment Lint should be silenced in autolayout

**Improvements**
- [ ] `Warning: DefaultNameUsage` to include suggestion

## New Widgets
- [ ] Button for Web, html5 `<button>` - https://github.com/gridaco/designto-code/pull/108
- [ ] TextField for Web, html5 `<input type="text">`
- [ ] Checkbox for Web, html5 `<input type="checkbox">`
- [ ] Form for Web, html5 `<form>`
- [ ] Anchor (Link) for Web, html4 `<a>`
    - [ ] alternative Link for NextJS
- [ ] Modal for Web
    - [ ] React
        - react-modal
        - @mui/base/Modal
        - @radix-ui/react-dialog
    - Vanilla
        - WIP
 - [ ] MouseRegion for Universal cursor & mouse event handling

## Motions
- [ ] React - framer-motion
- [ ] Vanilla - [popmotion](https://github.com/Popmotion/popmotion)

## `on` Events
- [ ] onClick
- [ ] onHover

## Fix of Known Issues
- [ ] Incomplete Flex Support with Figma Autolayout
    - [ ] https://github.com/gridaco/designto-code/issues/99
    - [ ] https://github.com/gridaco/designto-code/issues/93
    - [ ] https://github.com/gridaco/designto-code/issues/32
- [ ] Dart Formatting Issue
- [ ] Dart lang & Flutter Support based on [CoLI](https://github.com/gridaco/CoLI)
- [ ] Text font-weight mapper mismatching style - from https://github.com/gridaco/designto-code/issues/27

## Indeterminate

> Below features are not critically related to this milestone, but are highly likely to be implemented if the schedule allow us.

- Complete Variant Support
- Realtime In-browser React Compiler
- html5 Form support
- React Modal support
- https://github.com/gridaco/designto-code/issues/86
- https://github.com/gridaco/designto-code/issues/88
- https://github.com/gridaco/designto-code/issues/89
- https://github.com/gridaco/designto-code/issues/72
- https://github.com/gridaco/designto-code/issues/59

## Will not be supported
- Non tracked, non standard Component instantiation (Custom overrides on Instance)
- Remote Components from Shared Library
- Flutter Updates - this Milestone is focused on Responsive Web dev with ReactJS. It will contain minimal Flutter updates.

## Editor Updates

- [ ] Assets download interface & asset management / preference
- [ ] New Look & Workspace for Responsive Web development
- [ ] Framework Configuration
- [ ] Architecture & Project Configuration Menu
- [ ] Design Lint support on editor (previously only available via [Grida Assistant](https://github.com/gridaco/assistant))

## Docs & Examples Updates

**docs/guides to be added**
- [ ] Design Responsive Page with Breakpoints
- [ ] Design Responsive Component with Variants

**Examples to be added**
- [ ] example design of spa landingpage + repo
