### ISSUE TITLE
[📌 Roadmap] Web frameworks support - React / Vue / Svelte / Vanilla

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/designto-code#36]
## React
- [ ] styled-components
- [ ] styled-components (emotion)
- [ ] styled-components (styled-components)
- [ ] css in jsx
- [ ] css + jsx
- [ ] class components
- [ ] small components as const

## Vue
- [ ] vue scoped style css

## Svelte
WIP

## Vanilla
complete
