### ISSUE TITLE
[Roadmap] 0.9.0 Release

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/designto-code#53]
checklist

- [ ] https://github.com/gridaco/designto-code/issues/46
- [ ] https://github.com/gridaco/designto-code/issues/43
- [ ] https://github.com/gridaco/designto-code/issues/42
- [ ] https://github.com/gridaco/designto-code/issues/37
- [ ] https://github.com/gridaco/designto-code/issues/32
- [ ] https://github.com/gridaco/designto-code/issues/33
- [ ] https://github.com/gridaco/designto-code/issues/35
